### ISSUE TITLE
UI Enhancement : Add Scrolling Effect 

### ISSUE THREAD

**Issue by codewithunknown** [uyuni-project/uyuni-project.github.io#101]
## Details
As part of https://github.com/openSUSE/mentoring/issues/205,The goal of this issue is to implement a scrolling effect on the Uyuni Project image displayed in the provided link. The desired effect is to make the image appear as if it is revolving or moving when the user scrolls.
![image](https://github.com/uyuni-project/uyuni-project.github.io/assets/126901279/286a5074-13de-4548-a5ff-64235ff34696)

## Proposed Solution
To achieve the scrolling effect without relying on JavaScript dependencies, we can utilize CSS animations combined with scroll events. Here's a proposed solution:

HTML Structure: Place the image within a container element.

```html
<div class="image-container">
    <img src="" alt="Uyuni Project Image">
</div>
```
CSS Styling: Apply necessary CSS styles to the container and image to prepare for the scrolling effect.

```css
.image-container {
    overflow: hidden;
    width: 100%;
    height: 400px; /* Adjust height as needed */
    position: relative;
}

.image-container img {
    width: 100%;
    height: auto;
    position: absolute;
    top: 0;
    left: 0;
}
```
CSS Animation: Define a CSS animation that will create the revolving effect.

```css
@keyframes scroll {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
```
Apply Animation on Scroll: Trigger the animation when the user scrolls.

```css
.image-container img {
    /* Other styles */
    animation: scroll 10s infinite linear; /* Adjust timing as needed */
}
```
Adjust the duration (10s in this example) and timing function (linear in this example) of the animation according to preference.

Optional: Fine-tune the animation properties such as easing, duration, and direction to achieve the desired scrolling effect.

With this solution, the image should exhibit a revolving effect when the user scrolls, providing an engaging visual experience without the need for JavaScript dependencies.

cc : @deneb-alpha
